name: NGINX CI/CD Demo

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Login To DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-cicd-demo .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx-cicd-demo

    - name: SSH to EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/nginx-cicd-demo
          docker stop nginx-demo || true
          docker rm nginx-demo || true
          docker run -d --name nginx-demo -p 80:80 ${{ secrets.DOCKER_USERNAME }}/nginx-cicd-demo
